apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-blue
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
      version: blue
  template:
    metadata:
      labels:
        app: bankapp
        version: blue
    spec:
      imagePullSecrets:
        - name: regcred   # <- reference your Docker Hub secret
      containers:
        - name: bankapp
          image: deepti2409/bankapp:blue
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Test@123
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1000Mi"
          imagePullPolicy: Always
